// API pública del motor: lo único que el resto de la app puede importar de `engine/`.
export * from './schema'
export * from './patterns'
export * from './sim/types'
export * from './sim/sim'
export * from './sim/timeline'
export * from './circuit/geometry'
export * from './circuit/patch'
export * from './circuit/compile'
export * from './code/regions'
export * from './level/variants'
export * from './level/define'
export * from './code/diff'
