import type { Catalog } from '../../i18n'

// Traducción al inglés del contenido de este nivel (texto en español → inglés).
const en: Catalog = {
  'Sucursales y pagos': 'Branches and payments',
  'Dos problemas conocidos en el mismo circuito: el flujo compartido le da lattes a Montaña, y Cobrar pierde los pagos con vale. Cada uno está en un punto de variación distinto.': 'Two known problems in the same circuit: the shared flow gives lattes to Mountain, and Charge loses voucher payments. Each one is at a different point of variation.',
  'Resolver los dos sockets: cada sucursal su bebida y cada método de pago su cartucho.': 'Solve both sockets: each branch its own drink and each payment method its own cartridge.',
  'Cliente': 'Customer',
  'Tomar pedido': 'Take order',
  'Crear bebida': 'Create drink',
  'Frappé': 'Frappé',
  'Latte': 'Latte',
  'Cobrar': 'Charge',
  'Preparar': 'Prepare',
  'Entregar': 'Hand over',
  'Efectivo': 'Cash',
  'Tarjeta': 'Card',
  'Vale': 'Voucher',
  'Envoltura': 'Wrapper',
  'Sucursal': 'Branch',
  'Centro': 'Downtown',
  'Playa': 'Beach',
  'Montaña': 'Mountain',
  'Fábrica única': 'Single factory',
  'Tamaño': 'Size',
  'Temperatura': 'Temperature',
  'Factory Method decide qué se crea': 'Factory Method decides what gets created',
  'Cada sucursal es una subclase con su propio molde. Convive sin problema con Strategy: uno responde "qué objeto crear", el otro "cómo hacer algo con él".': 'Each branch is a subclass with its own mold. It lives happily alongside Strategy: one answers "what object to create", the other "how to do something with it".',
  'Singleton: todas las sucursales reciben lo mismo': 'Singleton: every branch gets the same thing',
  'Una fábrica única no sabe de qué sucursal viene cada pedido. La creación tenía que variar, no compartirse.': 'A single factory doesn\'t know which branch each order comes from. Creation had to vary, not be shared.',
  'Builder arma, no elige la clase': 'Builder builds, it doesn\'t pick the class',
  'Armar la bebida por pasos no cambia que el if del flujo compartido siga eligiendo mal para Montaña.': 'Building the drink in steps doesn\'t change the fact that the if in the shared flow still picks wrong for Mountain.',
  'Método de pago': 'Payment method',
  'Strategy decide cómo se cobra': 'Strategy decides how to charge',
  'Cada forma de pago es un cartucho intercambiable. No le importa qué fábrica creó la bebida: los patrones se combinan porque cada uno atiende su propio punto de variación.': 'Each payment method is a swappable cartridge. It doesn\'t care which factory created the drink: patterns combine because each one handles its own point of variation.',
  'Observer cobra en todos lados': 'Observer charges everywhere',
  'Avisar a todos los métodos de pago hace que cada uno cobre el mismo pedido.': 'Notifying every payment method makes each one charge the same order.',
  'Decorator envuelve, no elige': 'Decorator wraps, it doesn\'t choose',
  'El pedido sale envuelto de Cobrar, pero el vale ya se perdió en el árbol de if.': 'The order leaves Charge wrapped, but the voucher was already lost in the if tree.',
  'Centro · efectivo': 'Downtown · cash',
  'Playa · tarjeta': 'Beach · card',
  'Montaña · vale': 'Mountain · voucher',
  'Montaña · tarjeta': 'Mountain · card',
}

export default en
