import type { Catalog } from '../../i18n'

// Traducción al inglés del contenido de este nivel (texto en español → inglés).
const en: Catalog = {
  'Pedidos en vivo': 'Live orders',
  'Un pedido recibe eventos en vivo. Un "entregar" enviado por error no se puede deshacer, el pedido acepta eventos que no tienen sentido, y cuando cambia de estado solo la pantalla se entera.': 'An order receives live events. A "hand over" sent by mistake can\'t be undone, the order accepts events that make no sense, and when it changes state only the display finds out.',
  'Deshacer a tiempo lo enviado por error, rechazar lo que no aplica y avisar a todos los interesados.': 'Undo what was sent by mistake in time, reject what doesn\'t apply and notify everyone interested.',
  'Eventos': 'Events',
  'Mostrador': 'Counter',
  'Deshacer': 'Undo',
  'Pedido': 'Order',
  'Avisar cambio': 'Notify change',
  'Pantalla': 'Display',
  'Lealtad': 'Loyalty',
  'Rechazar evento': 'Reject event',
  'Cola': 'Queue',
  '🔔 pantalla': '🔔 display',
  '🔔 lealtad': '🔔 loyalty',
  '✋ evento rechazado': '✋ event rejected',
  'pendiente': 'pending',
  'pagado': 'paid',
  'preparando': 'preparing',
  'entregado': 'delivered',
  'cancelado': 'cancelled',
  'Command: eventos que se pueden retirar': 'Command: events you can withdraw',
  'Cada evento es una tarjeta en cola. El "entregar" enviado por error se retira antes de que llegue al pedido.': 'Each event is a card in a queue. The "hand over" sent by mistake is withdrawn before it reaches the order.',
  'Una cadena no deshace': 'A chain doesn\'t undo',
  'Pasar la cancelación de mano en mano no sirve si el evento ya se ejecutó: nadie puede atenderla.': 'Passing the cancellation from hand to hand doesn\'t help if the event already ran: nobody can handle it.',
  'Un proxy no vuelve en el tiempo': 'A proxy doesn\'t turn back time',
  'Un intermediario delante del pedido no guarda los eventos como objetos que se puedan retirar.': 'A middleman in front of the order doesn\'t keep the events as objects that can be withdrawn.',
  'Estados': 'States',
  'State: cada estado sabe qué acepta': 'State: each state knows what it accepts',
  'Cancelar algo ya entregado se rechaza en el estado "entregado", sin ifs repartidos.': 'Cancelling something already delivered is rejected in the "delivered" state, with no ifs scattered around.',
  'Strategy la elige quien llama; en State decide el estado actual': 'The caller picks the Strategy; in State the current state decides',
  'Una estrategia por evento aplica su cambio sin saber en qué estado está el pedido. En State decide el estado actual, y normalmente él mismo indica el siguiente.': 'One strategy per event applies its change without knowing what state the order is in. In State the current state decides, and it usually sets the next one itself.',
  'Un esqueleto fijo no valida transiciones': 'A fixed skeleton doesn\'t validate transitions',
  'Template Method fija el orden de unos pasos; aquí el problema es qué eventos tienen sentido según el estado.': 'Template Method fixes the order of some steps; here the problem is which events make sense depending on the state.',
  'Avisos': 'Notifications',
  'Observer: cada cambio llega a todos': 'Observer: every change reaches everyone',
  'Pantalla y Lealtad se suscriben al pedido. Los tres patrones conviven: Command decide qué llega, State qué se acepta, Observer quién se entera.': 'Display and Loyalty subscribe to the order. The three patterns live together: Command decides what arrives, State what is accepted, Observer who finds out.',
  'Facade no difunde': 'Facade doesn\'t broadcast',
  'Una puerta simple para avisar sigue llamando a quien conoce: Lealtad sigue sin enterarse.': 'A simple door for notifying still calls whoever it knows: Loyalty still doesn\'t find out.',
  'Singleton no suma interesados': 'Singleton doesn\'t add listeners',
  'Tener un único notificador compartido no cambia a quién le avisa.': 'Having a single shared notifier doesn\'t change who it notifies.',
  'pagar': 'pay',
  'entregar (por error)': 'hand over (by mistake)',
  'deshacer entregar': 'undo hand over',
  'preparar': 'prepare',
  'entregar': 'hand over',
  'cancelar (ya entregado)': 'cancel (already delivered)',
}

export default en
